<div align='center'><font color='blue'>
<h2>Estudo de Caso</h2>
<h3>Limpeza e Pré-Processamento de Dados com Numpy</h3></font>
</div>

- Serão utilizados dados reais publicados em: https://www.openintro.org/data/index.php?data=loans_full_schema
- Esse  conjunto  de  dados  representa  milhares  de  empréstimos  feitos  por  meio  da plataforma  Lending  Club,  que  é  uma  plataforma  que  permite  que  indivíduos  emprestem  para outros indivíduos.
- Além  disso  será usado  um  dataset  com  cotação  do  dólar  em  relação  ao  Euro.  Extraímos uma pequena amostra de dados do site: https://finance.yahoo.com.

<font color='blue'><h3>Etapas do projeto:</h3> \
Etapa 1 - Manipulação e Tratamento das Colunas do tipo String \
Etapa 2 - Manipulação e Tratamento das Colunas Numéricas \
Etapa 3 - Carregar Segundo Dataset para trabalhar em conjunto \
Etapa 4 - 
    </font>

In [1]:
from platform import python_version
print('A versão do Python utilizada nesse projeto é', python_version())

A versão do Python utilizada nesse projeto é 3.9.7


In [2]:
import numpy as np

In [3]:
%reload_ext watermark
%watermark --iversion

numpy: 1.20.3



In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Configuração de impressão do Numpy
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

### Carregando os dados

In [6]:
dados = np.genfromtxt('dados/dataset1.csv', 
                      delimiter = ';', 
                      skip_header = 1, 
                      autostrip = True, 
                      encoding = 'cp1252')

In [7]:
type(dados)

numpy.ndarray

In [8]:
dados.shape

(10000, 14)

In [9]:
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

- O dataset foi carregado com as colunas de string com valores 'nan'

### Verificando valores ausentes

In [10]:
np.isnan(dados).sum()

88005

In [11]:
# soma o maior valor + 1 ignora valores nan
# Esse valor aleatório será usado para preencher os valores ausentes no momento da carga de dados de variáveis
# numéricas e depois será tratado esse valor como valor ausente
valor_um = np.nanmax(dados) + 1
print(valor_um)

68616520.0


In [12]:
# Calcula a média (variáveis numéricas) ignorando valores nan por coluna
# Será usado para separar variáveis numéricas das variáveis de string
media_ignorando_nan = np.nanmean(dados, axis = 0)
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [13]:
# Colunas do tipo string com valores ausentes
colunas_strings = np.argwhere(np.isnan(media_ignorando_nan)).squeeze() ; colunas_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [14]:
# Colunas do tipo numérico
colunas_num = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze(); colunas_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

- Carregar dataset separando colunas numéricas de strings

In [15]:
arr_string = np.genfromtxt('dados/dataset1.csv', 
                           delimiter = ';', 
                           skip_header = 1, 
                           autostrip = True, 
                           encoding = 'cp1252', 
                           usecols = colunas_strings,
                           dtype = str)

In [16]:
arr_string

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [17]:
arr_string.shape

(10000, 8)

In [18]:
arr_num = np.genfromtxt('dados/dataset1.csv',
                         delimiter = ';',
                         skip_header = 1,
                         autostrip = True,
                         encoding ='cp1252',
                         usecols = colunas_num,
                         filling_values = valor_um) ; arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

- Carrega o cabeçalho do dataset, separando as colunas strings das colunas numéricas

In [19]:
arr_cabecalho = np.genfromtxt('dados/dataset1.csv',
                             delimiter = ';',
                             skip_footer = dados.shape[0],
                             autostrip= True,
                             dtype = str,
                             encoding = 'cp1252'); arr_cabecalho

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [20]:
header_string, header_num = arr_cabecalho[colunas_strings], arr_cabecalho[colunas_num]; 

In [21]:
header_string 

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [22]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Função de checkpoint
- Serão criadas funções de checkpoint para salvar os resultados intermédiários

#### Checkpoint 1

In [23]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + '.npz')
    return(checkpoint_variable)

In [24]:
checkpoint_inicial = checkpoint('dados/checkpoint-inicial', header_string, arr_string)

In [25]:
checkpoint_inicial['data']

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [26]:
np.array_equal(checkpoint_inicial['data'], arr_string)

True

<font color= 'blue'><h3>ETAPA 1 - Manipulação e Tratamento das Colunas do tipo String</h3></font>

### Pré-Processamento da Variável issue_date com Label Encoding
- Label encoding: Converter as categorias de uma variável para sua representação numérica correspondente

In [27]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [28]:
header_string[0] = 'issue_date' ; header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [29]:
np.unique(arr_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [30]:
# Extrai o sufixo 15 da variável issue_date e converte em um array
arr_string[:,0] = np.chararray.strip(arr_string[:,0], '-15')

In [31]:
# Extrai os valores únicos
np.unique(arr_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [32]:
# Cria um array com os meses(incluindo o elemento vazio para o que estiver em branco)
meses = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [33]:
# Loop para converter os nomes dos meses em valores numéricos(Label encoding)
for i in range(13):
    arr_string[:,0] = np.where(arr_string[:,0] == meses[i], i, arr_string[:,0])

In [34]:
np.unique(arr_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Pré-Processamento da Variável loan_status com Binarização
Essa variável indica o status da pessoa em relação a empréstimo, se está em atraso ou não. Será classificado de acordo com dois status:
- Classe positiva = 1
- Classe negativa = 0

In [35]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [36]:
np.unique(arr_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [37]:
# Número de elementos
np.unique(arr_string[:,1]).size

9

In [38]:
# Criação de um array com 3 posições
status = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [39]:
# Verifica os valores da variável e compara com o array anterior convertendo a variável para valores binários(Binarização)
arr_string[:,1] = np.where(np.isin(arr_string[:,1], status), 0, 1)

In [40]:
# Extrai os valores únicos 
np.unique(arr_string[:,1])

array(['0', '1'], dtype='<U69')

### Pré-Processamento da variável term com Limpeza de String
Essa variável indica o período do empréstimo

In [41]:
header_string[2] = 'term_months'

In [42]:
# Valores únicos
np.unique(arr_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [43]:
# Remove a palavra 'months'(colocar com espaço)
arr_string[:,2] = np.chararray.strip(arr_string[:,2], ' months'); arr_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [44]:
# Substitui valores ausente com o valor 60
arr_string[:,2] = np.where(arr_string[:,2]== '', '60', arr_string[:,2]) ; np.unique(arr_string[:,2])

array(['36', '60'], dtype='<U69')

### Pré-Processamento das Variáveis grade e sub_grade com Dicionário(Tipo de Label Encoding)
As variáveis 'grade' e 'sub_grade' indicam classificações relacionadas ao caráter de pagamento das pessoas.
As variáveis são parecidas, então utilizaremos a variável sub_grade por obter informações mais detalhadas.
Ajuste da variável sub_grade:
- Como as duas variáveis possuem valor ausente, vamos tratar a 'sub_grade com ajuda da variável 'grade'.
- Será criado uma nova categoria na variável 'sub_grade' para substituir os valores ausentes.
- Será deletada a variável 'grade'.
- A variável 'sub_grade' terá sua representação numérica.

In [45]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [46]:
np.unique(arr_string[:,3], return_counts = True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

In [47]:
np.unique(arr_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267, 250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2], dtype=int64))

In [48]:
# Retira a primeira linha, que é um valor ausente, da variável 'grade'
np.unique(arr_string[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [49]:
# Loop para tratar o 'sub_grade'
for i in np.unique(arr_string[:,3])[1:]:
    arr_string[:,4] = np.where((arr_string[:,4] == '') & (arr_string[:,3] == i), i + '5', arr_string[:,4])

In [50]:
# Retorna categorias e suas respectivas contagens
np.unique(arr_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

Tratamento dos valores ausentes da variável 'sub_grade'

In [51]:
# Os valores ausente serão substituídos por uma nova categoria
arr_string[:,4] = np.where(arr_string[:,4] == '', 'H1', arr_string[:,4])

In [52]:
np.unique(arr_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Remoção da variável 'grade'

In [53]:
arr_string = np.delete(arr_string, 3, axis = 1); arr_string.shape

(10000, 7)

In [54]:
# Remoção do nome 'grade' o cabeçalho
header_string = np.delete(header_string, 3);

In [55]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [56]:
# Verificar nova variável com índice 3(que era a posição da variável 'grade')
arr_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [57]:
# Verificar nova variável com índice 3(que era a posição da variável 'grade')
header_string[3]

'sub_grade'

Conversão da variável 'sub_grade' para representação numérica

In [58]:
np.unique(arr_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [59]:
keys = list(np.unique(arr_string[:,3])) ; keys[0:5]

['A1', 'A2', 'A3', 'A4', 'A5']

In [60]:
# Criação de uma lista de valores
values = list(range(1, np.unique(arr_string[:,3]).shape[0] + 1)); values[0: 5]

[1, 2, 3, 4, 5]

In [61]:
# Criação do dicionário
dict_sub_grade = dict(zip(keys, values)); dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [62]:
# Loop para substituir a string com as categorias pela representação numérica (frequência)
for i in np.unique(arr_string[:,3]):
    arr_string[:,3] = np.where(arr_string[:,3] == i, dict_sub_grade[i], arr_string[:,3])

In [63]:
np.unique(arr_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

### Pré-Processamento da Variável Verification status com Binarização
Essa variável indica o status de verificação do empréstimo.
- A variável contém 3 tipos de registros sendo dois deles aparentemente parecidos. Então esses tornarão um só.
- Como o conceito de binarização utiliza apenas 0 ou 1, o valor '0' será atribuido ao status de 'não verificado' e o '1' para 'status verificado'.
- Os valores ausentes receberão o valor '0', pois sem o registro não sabemos se a informação foi verificada ou não então optamos por torná-la 'não verificada'.

In [64]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [65]:
np.unique(arr_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [66]:
# Binarização
arr_string[:,4] = np.where((arr_string[:,4] == '')| (arr_string[:,4] == 'Not Verified'), 0, 1)

In [67]:
# Verificação dos valores únicos
np.unique(arr_string[:,4])

array(['0', '1'], dtype='<U69')

### Pré-Processamento da Variável url com Extração de ID
Verificamos que os registros nessa variável seguem um padrão e a única diferença entre os registros é pelo 'loan_id' localizado ao final da url.
- Será extraído o valor do id na url.
- O conjunto de dados possui uma variável do tipo int chamada 'id'.Iremos comparar os valores das duas colunas verificando se possuem valores iguais.
- A variável 'url' será excluída por conter valores iguais aos da coluna 'id'.

In [68]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [69]:
np.unique(arr_string[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [70]:
# Extração do id ao final da url
np.chararray.strip(arr_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [71]:
# Atribuição do valor do id extraído à variável 'url'
arr_string[:,5] = np.chararray.strip(arr_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [72]:
# Transformação da variável para int32
arr_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [73]:
# Comparação de valores das colunas 'id' e 'url' 
np.array_equal(arr_num[:,0].astype(dtype = np.int32), arr_string[:,5].astype(dtype = np.int32))

True

A variável 'url' será deletada por conter valores idênticos a coluna 'id'

In [74]:
# Remoção da variável 'url'
arr_string = np.delete(arr_string, 5, axis = 1)

In [75]:
# Remoção do nome da coluna no cabeçalho
header_string = np.delete(header_string, 5)

In [76]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

### Pré-Processamento da Variável 'address' com Categorização
Essa variável representa o endereço do Estado que a pessoa mora.
- Será alterado o nome da variável para melhor identificação.
- Será tratado o valor ausente. 
- Como possui vários Estados, vamos dividí-los por suas regiões.
- As regiões receberão classificação numérica.

In [77]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [78]:
# Valores da variável 
arr_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [79]:
# Alteração do nome da variável
header_string[5] = 'state_address'

In [80]:
# Extrai nome e contagem
state, state_count = np.unique(arr_string[:,5], return_counts = True)

In [81]:
# Ordena de forma decrescente
state_address_ord = np.argsort(-state_count);

In [82]:
# Imprime
state[state_address_ord], state_count[state_address_ord]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64))

In [83]:
# Tratamento do valor ausente
arr_string[:,5] = np.where(arr_string[:,5] == '', 0, arr_string[:,5])

Vamos separar os estados por regiões. Referência: https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [84]:
# Separação dos estados por regiões
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [85]:
# Substituição de cada estado pelo id da sua região
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_west), 1, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_south), 2, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_midwest), 3, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_east), 4, arr_string[:,5])

In [86]:
# Verificação
np.unique(arr_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Conversão do Array de Strings para Inteiro

In [87]:
arr_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [88]:
# Converte os valores para inteiro
arr_string = arr_string.astype(int)

In [89]:
arr_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [90]:
arr_string.dtype

dtype('int32')

### Checkpoint com Variáveis do Tipo String Limpas e Pré-Processadas
**Checkpoint2**

In [91]:
checkpoint_string = checkpoint('dados/Checkpoint-String', header_string, arr_string)

In [92]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [93]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [94]:
np.array_equal(checkpoint_string['data'], arr_string)

True

<font color= 'blue'><h3>ETAPA 2 - Manipulação e Tratamento das Colunas Numéricas</h3></font>

- Será criado um array de estatísticas

In [95]:
# Vizualização dos dados
arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [96]:
# Nomes das colunas numéricas
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [97]:
# Não temos valor ausente, pois ao carregar os dados substituímos por um valor arbitrário
np.isnan(arr_num).sum()

0

In [98]:
valor_um

68616520.0

In [99]:
# Verificar se uma coluna foi preenchida com valor_um
np.isin(arr_num[:,0], valor_um).sum()

0

Vamos criar um array de estatísticas, especificamente valor mínimo, máximo e média de cada variável. Será usado para tratamento de valores ausentes (preenchidos com o valor_um).

In [100]:
# Criamos um array com valor mínimo, média e valor máximo ignorando nan
# Usaremos isso no tratamento de valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis = 0)])

In [101]:
arr_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,       31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,      440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,     1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [102]:
arr_stats[:, colunas_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Pré-Processamento da Variável funded_amnt

In [103]:
# Visualiza dados
arr_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [104]:
arr_stats[0,colunas_num[2]]

1000.0

In [105]:
# Ajustamos o conteúdo da coluna
arr_num[:,2] = np.where(arr_num[:,2] == valor_um, arr_stats[0,colunas_num[2]], arr_num[:,2])

In [106]:
arr_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Pré-Processamento das Variáveis loan_amnt, int_rate, installment e total_pymnt

In [107]:
# Nomeas das colunas
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [108]:
# Loop para substituir o valor ausente(valor_um) pelos valores do array de estatísticas
for i in [1,3,4,5]:
    arr_num[:,i] = np.where(arr_num[:,i] == valor_um, arr_stats[2, colunas_num[i]], arr_num[:,i])

In [109]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

<font color= 'blue'><h3>ETAPA 3 - Carregar Segundo Dataset para trabalhar em conjunto</h3></font>

### Trabalhando com o Segundo Dataset
O segundo dataset fornece os dados de cotação USD - EURO. Cada linha do dataset corresponde à taxa de câmbio para um mês em um ano.
- Usaremos o arr_string por possuir a variável issue_date(mês do empréstimo) para inserir a taxa de cotação do mês
- Será criada uma nova variável 
- Será tratado o valor ausente pela média das cotações
- Como o dataset está em dólar, vamos acrescentar as informações em euros utilizando a taxa de câmbio por mês.

In [110]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt('dados/dataset2.csv',
                          delimiter = ',',
                         autostrip = True,
                         skip_header = 1,
                         usecols = 3)

In [111]:
# Visualiza
dados_cot

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [112]:
# Colunas
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [113]:
# A coluna 0 do arr_string é o mês
arr_string[:,0].min()

0

In [114]:
# Atribuição da coluna de mês à nova variável
taxa_cambio = arr_string[:,0]

In [115]:
taxa_cambio

array([ 5,  0,  9, ...,  6,  4, 12])

In [116]:
# Loop para trocar os valores da variável taxa_cambio(mês) para o valor da taxa de cambio referente àquele mês
# Usamos dados_cot[i -1] devido a forma como carregamos os meses para comportar o zero
# lembrando: a numeração dos meses da issue_date vai de 0 a 12, o valor 0 foi aplicado para preencher valores nulos
for i in range(1, 13):
    taxa_cambio = np.where(taxa_cambio == i, dados_cot[i - 1], taxa_cambio)

In [117]:
taxa_cambio

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [118]:
# Substituiremos o valor 0 pela média
taxa_cambio = np.where(taxa_cambio == 0, np.mean(dados_cot), taxa_cambio)

In [119]:
taxa_cambio

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [120]:
taxa_cambio.shape

(10000,)

In [121]:
np.array_equal(taxa_cambio.shape[0], arr_string.shape[0])

True

In [122]:
taxa_cambio = np.reshape(taxa_cambio, (10000,1))

In [123]:
# Concatenação dos arrays
arr_num = np.hstack((arr_num, taxa_cambio))

In [124]:
# Inclui o nome da coluna no array de nomes
header_num = np.concatenate((header_num, np.array(['taxa_cambio'])))

Vamos criar colunas para as taxas de câmbio em USD e EURO.

In [125]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'taxa_cambio'], dtype='<U19')

In [126]:
# Criação de um array apenas com as colunas que fornecem valores em dólar
colunas_dolar = np.array([1,2,4,5])

In [127]:
# Visualiza
arr_num[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [128]:
# Shape
arr_num.shape

(10000, 7)

In [129]:
# Temos 4 colunas com valore em dólar então teremos 4 colunas com valores em euros
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in colunas_dolar:
    arr_num = np.hstack((arr_num, np.reshape(arr_num[:,i] / arr_num[:,6], (10000,1))))

In [130]:
# Shape
arr_num.shape

(10000, 11)

In [131]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

Vamos nomear as novas colunas criadas 

In [132]:
header_add = np.array([column_name + '_EUR' for column_name in header_num[colunas_dolar]])

In [133]:
header_add

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [134]:
header_num = np.concatenate((header_num, header_add))

In [135]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'taxa_cambio', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [136]:
# Acrescentando o _USD ao nome das colunas que estão em dólar 
header_num[colunas_dolar] = np.array([column_name + '_USD' for column_name in header_num[colunas_dolar]])

In [137]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'taxa_cambio', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [138]:
# Reordenando as colunas para melhorar a visualização
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [139]:
header_num = header_num[columns_index_order]

In [140]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'taxa_cambio'],
      dtype='<U19')

In [141]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [142]:
arr_num = arr_num[:, columns_index_order]

In [143]:
arr_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Pré_Processamento da Variável int_rate(taxa de juros)

In [144]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'taxa_cambio'],
      dtype='<U19')

In [145]:
arr_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [146]:
# Vamos colocar a taxa de juros no formato de porcentagem
arr_num[:,5] = arr_num[:,5] / 100

In [147]:
arr_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint com Variáveis Numéricas Limpas e Pré-Processadas
**Checkpoint 3**

In [148]:
checkpoint_num = checkpoint('dados/Checkpoint-Num', header_num, arr_num)

In [149]:
checkpoint_num['header'], checkpoint_num['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'taxa_cambio'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

### Construindo o Dataset final

In [150]:
checkpoint_string['data'].shape

(10000, 6)

In [151]:
checkpoint_num['data'].shape

(10000, 11)

In [152]:
# Concatena os arrays
df_final = np.hstack((checkpoint_num['data'], checkpoint_string['data']))

In [153]:
df_final

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [154]:
# Verifica se tem valor ausente
np.isnan(df_final).sum()

0

In [155]:
# Concatena os arrays de nomes de colunas
header_full = np.concatenate((checkpoint_num['header'], checkpoint_string['header']))

In [156]:
# Ordenando o dataset
df_final = df_final[np.argsort(df_final[:,0])]

In [157]:
df_final

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [158]:
# Conferindo a ordenação da coluna 0
np.argsort(df_final[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [159]:
# Concatena o array de nomes de colunas com o array de dados
df_final = np.vstack((header_full, df_final))

### Gravando o Dataset Final Limpo e Pré-Processado

In [160]:
# Salva em disco
np.savetxt("dados/dataset_limpo_preprocessado.csv", 
           df_final, 
           fmt = '%s',
           delimiter = ',')

### Fim